version: '3.9'
networks:
  deploy-network:
    driver: bridge
services:
  dota2tierlist.api:
    container_name: backend
    build:
      context: .
      dockerfile: DOTA2TierList.API/Dockerfile
    ports:
      - "80:80"
    networks:
      - deploy-network
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: DotaTierListDB
    ports:
      - "5432:5432"
    networks:
      - deploy-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:

      